## /configuration.yaml

homeassistant:
  name: Home
  latitude: !secret homeassistant.latitude
  longitude: !secret homeassistant.longitude
  elevation: !secret homeassistant.elevation
  unit_system: !secret homeassistant.unit_system
  time_zone: !secret homeassistant.time_zone
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
    - type: legacy_api_password

introduction:

frontend:

config:

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

sensor:
  - platform: yr

tts:
  - platform: google

auth:

http:
  api_password: !secret http.api_password
  trusted_networks: !secret http.trusted_networks

cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
